"""empty message

Revision ID: 9fc4dcb828ca
Revises: ae23ecabb790
Create Date: 2022-05-27 11:27:52.232473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc4dcb828ca'
down_revision = 'ae23ecabb790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venue', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'area_id')
    op.drop_table('areas')
    # ### end Alembic commands ###
